services:
  traffilearn.azurefunctions:
    image: ${DOCKER_REGISTRY-}traffilearnazurefunctions
    container_name: traffilearn.azurefunctions
    build:
      context: .
      dockerfile: TraffiLearn.AzureFunctions/Dockerfile
    environment:
      - SmtpClientSettings:Host=mailhog
      - SmtpClientSettings:Port=1025
      - SmtpClientSettings:Username=traffilearn-dummy@dummy
      - SmtpClientSettings:Password=
      - SmtpClientSettings:EnableSsl=false
    networks:
      - traffilearn-network

networks:
  traffilearn-network:
    external: 
      name: traffilearn_network